apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: managed-upgrade-operator
  annotations:
    name: annotation
spec:
  scopes:
  - Cluster
  phases:
  - name: crds
  - name: namespace
  - name: rbac
  - name: deploy
  - name: cleanup-rbac
  - name: cleanup-deploy
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: 'True'
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  config:
    openAPIV3Schema:
      properties:
        image:
          description: Operator image to deploy
          type: string
          default: None
      type: object
test:
  template:
  - name: config-with-proxy
    context:
      config:
        image: quay.io/repository/redhat-user-prod/openshift/managed-upgrade-operator:latest
      environment:
        openShift:
          version: "4.21.8"
        proxy:
          httpProxy: http
          httpsProxy: https
          noProxy: no...
