apiVersion: v1
kind: Template
metadata:
  name: selectorsyncset-template

parameters:
  - name: REGISTRY_IMG
    required: true
  - name: CHANNEL
    value: staging
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: true
  - name: REPO_NAME
    value: managed-upgrade-operator
    required: true
  - name: DISPLAY_NAME
    value: Managed Upgrade Operator
    required: true

objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      annotations:
        component-display-name: ${DISPLAY_NAME}
        component-name: ${REPO_NAME}
        telemeter-query: csv_succeeded{_id="$CLUSTER_ID",name=~"${REPO_NAME}.*",exported_namespace=~"openshift-.*",namespace="openshift-operator-lifecycle-manager"} == 1
      labels:
        managed.openshift.io/gitHash: ${IMAGE_TAG}
        managed.openshift.io/gitRepoName: ${REPO_NAME}
        managed.openshift.io/osd: "true"
      name: managed-upgrade-operator
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/managed: "true"
      resourceApplyMode: Sync
      resources:
        - apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-managed-upgrade-operator
            labels:
              openshift.io/cluster-monitoring: "true"
        - apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: managed-upgrade-operator-catalog
            namespace: openshift-managed-upgrade-operator
          spec:
            sourceType: grpc
            image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
            displayName: Managed Upgrade Operator
            publisher: Red Hat
        - apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: managed-upgrade-operator-og
            namespace: openshift-managed-upgrade-operator
          spec:
            targetNamespaces:
              - openshift-managed-upgrade-operator
        - apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
          spec:
            channel: ${CHANNEL}
            name: managed-upgrade-operator
            source: managed-upgrade-operator-catalog
            sourceNamespace: openshift-managed-upgrade-operator
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: muo-monitoring-reader
            namespace: openshift-monitoring
          rules:
          - apiGroups:
            - ""
            resources:
            - configmaps  
            - serviceaccounts
            - secrets
            - services
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - route.openshift.io
            resources:
            - routes
            verbs:
            - get
            - list
            - watch
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: muo-pullsecret-reader
            namespace: openshift-config
          rules:
          - apiGroups:
            - ""
            resources:
            - secrets
            verbs:
            - get
            - list
            - watch
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: muo-monitoring-reader
            namespace: openshift-monitoring
          roleRef:
            kind: Role
            name: muo-monitoring-reader
          subjects:
          - kind: ServiceAccount
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: muo-pullsecret-reader
            namespace: openshift-config
          roleRef:
            kind: Role
            name: muo-pullsecret-reader
          subjects:
          - kind: ServiceAccount
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator

