apiVersion: v1
kind: Template
metadata:
  name: selectorsyncset-template

parameters:
  - name: REGISTRY_IMG
    required: true
  - name: CHANNEL
    value: staging
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: true
  - name: REPO_NAME
    value: managed-upgrade-operator
    required: true
  - name: DISPLAY_NAME
    value: Managed Upgrade Operator
    required: true
  - name: OCM_VPCE_SERVICE_NAME_EAST
    required: true
  - name: OCM_VPCE_SERVICE_NAME_WEST
    required: true
  - name: OCM_DOMAIN
    required: true
  - name: OCM_HOSTNAME
    required: true   

objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      annotations:
        component-display-name: ${DISPLAY_NAME}
        component-name: ${REPO_NAME}
        telemeter-query: csv_succeeded{_id="$CLUSTER_ID",name=~"${REPO_NAME}.*",exported_namespace=~"openshift-.*",namespace="openshift-operator-lifecycle-manager"} == 1
      labels:
        managed.openshift.io/gitHash: ${IMAGE_TAG}
        managed.openshift.io/gitRepoName: ${REPO_NAME}
        managed.openshift.io/osd: "true"
      name: managed-upgrade-operator
    spec:
      clusterDeploymentSelector:
        matchLabels:
          api.openshift.com/managed: "true"
      resourceApplyMode: Sync
      resources:
        - apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-managed-upgrade-operator
            labels:
              openshift.io/cluster-monitoring: "true"
        - apiVersion: operators.coreos.com/v1alpha1
          kind: CatalogSource
          metadata:
            name: managed-upgrade-operator-catalog
            namespace: openshift-managed-upgrade-operator
          spec:
            sourceType: grpc
            grpcPodConfig:
              securityContextConfig: restricted
              nodeSelector:
                node-role.kubernetes.io: infra
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/infra
                operator: Exists
            image: ${REGISTRY_IMG}@${IMAGE_DIGEST}
            displayName: Managed Upgrade Operator
            publisher: Red Hat
        - apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: managed-upgrade-operator-og
            namespace: openshift-managed-upgrade-operator
            annotations:
              olm.operatorframework.io/exclude-global-namespace-resolution: 'true'
          spec:
            targetNamespaces:
              - openshift-managed-upgrade-operator
        - apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
          spec:
            channel: ${CHANNEL}
            name: managed-upgrade-operator
            source: managed-upgrade-operator-catalog
            sourceNamespace: openshift-managed-upgrade-operator
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: muo-monitoring-interactor
            namespace: openshift-monitoring
          rules:
          - apiGroups:
            - ""
            resources:
            - configmaps
            - serviceaccounts
            - secrets
            - services
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - route.openshift.io
            resources:
            - routes
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - ""
            resources:
            - serviceaccounts/token
            verbs:
            - create
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: muo-pullsecret-reader
            namespace: openshift-config
          rules:
          - apiGroups:
            - ""
            resources:
            - secrets
            verbs:
            - get
            - list
            - watch
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: muo-dvo-reader
            namespace: openshift-deployment-validation-operator
          rules:
          - apiGroups:
            - ""
            resources:
            - services
            verbs:
            - get
            - list
            - watch
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: muo-monitoring-interactor
            namespace: openshift-monitoring
          roleRef:
            kind: Role
            name: muo-monitoring-interactor
          subjects:
          - kind: ServiceAccount
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: muo-pullsecret-reader
            namespace: openshift-config
          roleRef:
            kind: Role
            name: muo-pullsecret-reader
          subjects:
          - kind: ServiceAccount
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: muo-dvo-reader
            namespace: openshift-deployment-validation-operator
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: muo-dvo-reader
          subjects:
          - kind: ServiceAccount
            name: managed-upgrade-operator
            namespace: openshift-managed-upgrade-operator
        - apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: allow-from-openshift-managed-upgrade-operator
            namespace: openshift-deployment-validation-operator
          spec:
            ingress:
            - from:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: openshift-managed-upgrade-operator
            podSelector: {}
            policyTypes:
            - Ingress
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      name: sss-muo-vpce-east
    spec:
      clusterDeploymentSelector:
        matchExpressions:
        - key: api.openshift.com/fedramp
          operator: In
          values:
          - "true"
        - key: hive.openshift.io/cluster-region
          operator: In
          values:
          - us-gov-east-1
        - key: api.openshift.com/private-link
          operator: In
          values:
          - "true"
        - key: appsre-prod
          operator: NotIn
          values:
          - "true"           
        matchLabels:
          api.openshift.com/managed: "true"
      resourceApplyMode: Sync
      resources:
      - apiVersion: avo.openshift.io/v1alpha2
        kind: VpcEndpoint
        metadata:
          name: managed-upgrade-operator
          namespace: openshift-managed-upgrade-operator
        spec:
          serviceName: ${OCM_VPCE_SERVICE_NAME_EAST}
          securityGroup:
            ingressRules:
              - fromPort: 443
                toPort: 443
                protocol: tcp
          vpc:
            autoDiscoverSubnets: true
          customDns:
            route53PrivateHostedZone:
              autoDiscoverPrivateHostedZone: false
              domainName: ${OCM_DOMAIN}
              record:
                hostname: ${OCM_HOSTNAME}
                externalNameService:
                  name: muo-vpce-svc
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      name: sss-muo-vpce-west
    spec:
      clusterDeploymentSelector:
        matchExpressions:
        - key: api.openshift.com/fedramp
          operator: In
          values:
          - "true"
        - key: hive.openshift.io/cluster-region
          operator: In
          values:
          - us-gov-west-1
        - key: api.openshift.com/private-link
          operator: In
          values:
          - "true"
        - key: appsre-prod
          operator: NotIn
          values:
          - "true"        
        matchLabels:
          api.openshift.com/managed: "true"
      resourceApplyMode: Sync
      resources:
      - apiVersion: avo.openshift.io/v1alpha2
        kind: VpcEndpoint
        metadata:
          name: managed-upgrade-operator
          namespace: openshift-managed-upgrade-operator
        spec:
          serviceName: ${OCM_VPCE_SERVICE_NAME_WEST}
          securityGroup:
            ingressRules:
              - fromPort: 443
                toPort: 443
                protocol: tcp
          vpc:
            autoDiscoverSubnets: true
          customDns:
            route53PrivateHostedZone:
              autoDiscoverPrivateHostedZone: false
              domainName: ${OCM_DOMAIN}
              record:
                hostname: ${OCM_HOSTNAME}
                externalNameService:
                  name: muo-vpce-svc
  