// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/managed-upgrade-operator/pkg/cluster_upgrader (interfaces: ClusterUpgraderBuilder)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	cluster_upgrader "github.com/openshift/managed-upgrade-operator/pkg/cluster_upgrader"
	reflect "reflect"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockClusterUpgraderBuilder is a mock of ClusterUpgraderBuilder interface
type MockClusterUpgraderBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockClusterUpgraderBuilderMockRecorder
}

// MockClusterUpgraderBuilderMockRecorder is the mock recorder for MockClusterUpgraderBuilder
type MockClusterUpgraderBuilderMockRecorder struct {
	mock *MockClusterUpgraderBuilder
}

// NewMockClusterUpgraderBuilder creates a new mock instance
func NewMockClusterUpgraderBuilder(ctrl *gomock.Controller) *MockClusterUpgraderBuilder {
	mock := &MockClusterUpgraderBuilder{ctrl: ctrl}
	mock.recorder = &MockClusterUpgraderBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClusterUpgraderBuilder) EXPECT() *MockClusterUpgraderBuilderMockRecorder {
	return m.recorder
}

// NewClient mocks base method
func (m *MockClusterUpgraderBuilder) NewClient(arg0 client.Client) (cluster_upgrader.ClusterUpgrader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", arg0)
	ret0, _ := ret[0].(cluster_upgrader.ClusterUpgrader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClient indicates an expected call of NewClient
func (mr *MockClusterUpgraderBuilderMockRecorder) NewClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockClusterUpgraderBuilder)(nil).NewClient), arg0)
}
