apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-managed-upgrade-operator
  name: trusted-ca-bundle
  annotations:
    package-operator.run/phase: deploy
    package-operator.run/collision-protection: IfNoController
  labels:
    config.openshift.io/inject-trusted-cabundle: 'true'
