# permissions for end users to edit upgradeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upgradeconfig-editor-role
rules:
- apiGroups:
  - upgrade.managed.openshift.io
  resources:
  - upgradeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upgrade.managed.openshift.io
  resources:
  - upgradeconfigs/status
  verbs:
  - get
