apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: preferredupgradestarttimes.upgrade.managed.openshift.io
spec:
  group: upgrade.managed.openshift.io
  names:
    kind: PreferredUpgradeStartTime
    listKind: PreferredUpgradeStartTimeList
    plural: preferredupgradestarttimes
    singular: preferredupgradestarttime
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PreferredUpgradeStartTime is the Schema for the preferredupgradestarttimes
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PreferredUpgradeStartTimeSpec defines the desired state of
              PreferredUpgradeStartTime
            properties:
              dayOfWeek:
                enum:
                - Monday
                - Tuesday
                - Wednesday
                - Thursday
                - Friday
                - Saturday
                - Sunday
                type: string
              timeUtc:
                description: Time in UTC like "01:00"
                format: ^([0-1][0-9]|[2][0-3]):([0-5][0-9])$
                type: string
            required:
            - dayOfWeek
            - timeUtc
            type: object
          status:
            description: PreferredUpgradeStartTimeStatus defines the observed state
              of PreferredUpgradeStartTime
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
