apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: adminfreezewindows.upgrade.managed.openshift.io
spec:
  group: upgrade.managed.openshift.io
  names:
    kind: AdminFreezeWindow
    listKind: AdminFreezeWindowList
    plural: adminfreezewindows
    singular: adminfreezewindow
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AdminFreezeWindow is the Schema for the adminfreezewindows API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AdminFreezeWindowSpec defines a freeze window set by SRE
            properties:
              fromUtc:
                properties:
                  dayOfMonth:
                    maximum: 31
                    minimum: 1
                    type: integer
                  dayOfWeek:
                    enum:
                    - Monday
                    - Tuesday
                    - Wednesday
                    - Thursday
                    - Friday
                    - Saturday
                    - Sunday
                    type: string
                  month:
                    enum:
                    - January
                    - February
                    - March
                    - April
                    - May
                    - June
                    - July
                    - August
                    - September
                    - October
                    - November
                    - December
                    type: string
                  time:
                    description: Time in UTC like "01:00"
                    format: ^([0-1][0-9]|[2][0-3]):([0-5][0-9])$
                    type: string
                  timestamp:
                    format: date-time
                    type: string
                  weekOfMonth:
                    maximum: 4
                    minimum: 1
                    type: integer
                required:
                - month
                - time
                type: object
              toUtc:
                properties:
                  dayOfMonth:
                    maximum: 31
                    minimum: 1
                    type: integer
                  dayOfWeek:
                    enum:
                    - Monday
                    - Tuesday
                    - Wednesday
                    - Thursday
                    - Friday
                    - Saturday
                    - Sunday
                    type: string
                  month:
                    enum:
                    - January
                    - February
                    - March
                    - April
                    - May
                    - June
                    - July
                    - August
                    - September
                    - October
                    - November
                    - December
                    type: string
                  time:
                    description: Time in UTC like "01:00"
                    format: ^([0-1][0-9]|[2][0-3]):([0-5][0-9])$
                    type: string
                  timestamp:
                    format: date-time
                    type: string
                  weekOfMonth:
                    maximum: 4
                    minimum: 1
                    type: integer
                required:
                - month
                - time
                type: object
            required:
            - fromUtc
            - toUtc
            type: object
          status:
            description: AdminFreezeWindowStatus defines the observed state of AdminFreezeWindow
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
