// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/managed-upgrade-operator/pkg/notifier (interfaces: Notifier)
//
// Generated by this command:
//
//	mockgen -destination=mocks/notifier.go -package=mocks github.com/openshift/managed-upgrade-operator/pkg/notifier Notifier
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	notifier "github.com/openshift/managed-upgrade-operator/pkg/notifier"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// NotifyState mocks base method.
func (m *MockNotifier) NotifyState(value notifier.MuoState, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyState", value, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyState indicates an expected call of NotifyState.
func (mr *MockNotifierMockRecorder) NotifyState(value, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyState", reflect.TypeOf((*MockNotifier)(nil).NotifyState), value, description)
}
