// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/managed-upgrade-operator/pkg/alertmanager (interfaces: AlertManagerSilencer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/alertManagerSilenceClient.go -package=mocks github.com/openshift/managed-upgrade-operator/pkg/alertmanager AlertManagerSilencer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	strfmt "github.com/go-openapi/strfmt"
	alertmanager "github.com/openshift/managed-upgrade-operator/pkg/alertmanager"
	silence "github.com/prometheus/alertmanager/api/v2/client/silence"
	models "github.com/prometheus/alertmanager/api/v2/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAlertManagerSilencer is a mock of AlertManagerSilencer interface.
type MockAlertManagerSilencer struct {
	ctrl     *gomock.Controller
	recorder *MockAlertManagerSilencerMockRecorder
	isgomock struct{}
}

// MockAlertManagerSilencerMockRecorder is the mock recorder for MockAlertManagerSilencer.
type MockAlertManagerSilencerMockRecorder struct {
	mock *MockAlertManagerSilencer
}

// NewMockAlertManagerSilencer creates a new mock instance.
func NewMockAlertManagerSilencer(ctrl *gomock.Controller) *MockAlertManagerSilencer {
	mock := &MockAlertManagerSilencer{ctrl: ctrl}
	mock.recorder = &MockAlertManagerSilencerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertManagerSilencer) EXPECT() *MockAlertManagerSilencerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAlertManagerSilencer) Create(matchers models.Matchers, startsAt, endsAt strfmt.DateTime, creator, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", matchers, startsAt, endsAt, creator, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAlertManagerSilencerMockRecorder) Create(matchers, startsAt, endsAt, creator, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlertManagerSilencer)(nil).Create), matchers, startsAt, endsAt, creator, comment)
}

// Delete mocks base method.
func (m *MockAlertManagerSilencer) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAlertManagerSilencerMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAlertManagerSilencer)(nil).Delete), id)
}

// Filter mocks base method.
func (m *MockAlertManagerSilencer) Filter(predicates ...alertmanager.SilencePredicate) (*[]models.GettableSilence, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range predicates {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Filter", varargs...)
	ret0, _ := ret[0].(*[]models.GettableSilence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *MockAlertManagerSilencerMockRecorder) Filter(predicates ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockAlertManagerSilencer)(nil).Filter), predicates...)
}

// List mocks base method.
func (m *MockAlertManagerSilencer) List(filter []string) (*silence.GetSilencesOK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", filter)
	ret0, _ := ret[0].(*silence.GetSilencesOK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAlertManagerSilencerMockRecorder) List(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAlertManagerSilencer)(nil).List), filter)
}

// Update mocks base method.
func (m *MockAlertManagerSilencer) Update(id string, endsAt strfmt.DateTime) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, endsAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAlertManagerSilencerMockRecorder) Update(id, endsAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlertManagerSilencer)(nil).Update), id, endsAt)
}
