// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/managed-upgrade-operator/pkg/drain (interfaces: NodeDrainStrategyBuilder)
//
// Generated by this command:
//
//	mockgen -destination=mocks/nodeDrainStrategyBuilder.go -package=mocks github.com/openshift/managed-upgrade-operator/pkg/drain NodeDrainStrategyBuilder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	logr "github.com/go-logr/logr"
	v1alpha1 "github.com/openshift/managed-upgrade-operator/api/v1alpha1"
	drain "github.com/openshift/managed-upgrade-operator/pkg/drain"
	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockNodeDrainStrategyBuilder is a mock of NodeDrainStrategyBuilder interface.
type MockNodeDrainStrategyBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockNodeDrainStrategyBuilderMockRecorder
	isgomock struct{}
}

// MockNodeDrainStrategyBuilderMockRecorder is the mock recorder for MockNodeDrainStrategyBuilder.
type MockNodeDrainStrategyBuilderMockRecorder struct {
	mock *MockNodeDrainStrategyBuilder
}

// NewMockNodeDrainStrategyBuilder creates a new mock instance.
func NewMockNodeDrainStrategyBuilder(ctrl *gomock.Controller) *MockNodeDrainStrategyBuilder {
	mock := &MockNodeDrainStrategyBuilder{ctrl: ctrl}
	mock.recorder = &MockNodeDrainStrategyBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeDrainStrategyBuilder) EXPECT() *MockNodeDrainStrategyBuilderMockRecorder {
	return m.recorder
}

// NewDefaultNodeDrainStrategy mocks base method.
func (m *MockNodeDrainStrategyBuilder) NewDefaultNodeDrainStrategy(c client.Client, logger logr.Logger, uc *v1alpha1.UpgradeConfig, cfg *drain.NodeDrain) (drain.NodeDrainStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDefaultNodeDrainStrategy", c, logger, uc, cfg)
	ret0, _ := ret[0].(drain.NodeDrainStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewDefaultNodeDrainStrategy indicates an expected call of NewDefaultNodeDrainStrategy.
func (mr *MockNodeDrainStrategyBuilderMockRecorder) NewDefaultNodeDrainStrategy(c, logger, uc, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDefaultNodeDrainStrategy", reflect.TypeOf((*MockNodeDrainStrategyBuilder)(nil).NewDefaultNodeDrainStrategy), c, logger, uc, cfg)
}

// NewNodeDrainStrategy mocks base method.
func (m *MockNodeDrainStrategyBuilder) NewNodeDrainStrategy(c client.Client, logger logr.Logger, uc *v1alpha1.UpgradeConfig, cfg *drain.NodeDrain) (drain.NodeDrainStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewNodeDrainStrategy", c, logger, uc, cfg)
	ret0, _ := ret[0].(drain.NodeDrainStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewNodeDrainStrategy indicates an expected call of NewNodeDrainStrategy.
func (mr *MockNodeDrainStrategyBuilderMockRecorder) NewNodeDrainStrategy(c, logger, uc, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewNodeDrainStrategy", reflect.TypeOf((*MockNodeDrainStrategyBuilder)(nil).NewNodeDrainStrategy), c, logger, uc, cfg)
}
